[package]
name = "kafka_consumer"
version = "0.1.1"
edition = "2021"

[dependencies]
rdkafka = { version = "0.28", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
async-nats = "0.39"
dotenv = "0.15"
